import type { Metadata } from "next";
import LegalHeader from "../LegalHeader";
import SiteFooter from "../SiteFooter";
export const dynamic = "force-static";
export const metadata: Metadata = {title:"Aviso de privacidad | Hammurabi Risk",description:"Conoce cómo Hammurabi Risk recaba, utiliza y protege tus datos personales."};

export default function PrivacyPage(){return <main className="legal-page"><LegalHeader/><section className="legal-hero shell"><p className="eyebrow">Transparencia y confianza</p><h1>Aviso de privacidad.</h1><p className="lead">Te explicamos de forma clara qué datos tratamos, para qué los usamos y cómo puedes ejercer tus derechos.</p><p className="legal-updated">Última actualización: 23 de agosto de 2026</p></section><section className="legal-content shell"><aside className="legal-index" aria-label="Contenido"><strong>En esta página</strong><a href="#responsable">Responsable</a><a href="#datos">Datos que recabamos</a><a href="#finalidades">Finalidades</a><a href="#derechos">Derechos ARCO</a><a href="#transferencias">Transferencias</a><a href="#cookies">Cookies</a><a href="#cambios">Cambios</a></aside><div className="legal-copy">
<h2 id="responsable">1. Responsable del tratamiento</h2><p>Hammurabi Risk (en adelante, “Hammurabi Risk”), con domicilio en Plaza Hatria, Blvd. Gómez Morín, local 17, Ciudad Juárez, Chihuahua, es responsable del tratamiento de los datos personales recabados mediante este sitio, WhatsApp, correo electrónico, teléfono y nuestros canales de atención.</p><p>Para asuntos de privacidad puedes escribir a <a href="mailto:aguilar@grupohammurabi.com">aguilar@grupohammurabi.com</a> o llamar al <a href="tel:+526561423870">656 142 3870</a>.</p>
<h2 id="datos">2. Datos personales que podemos recabar</h2><ul><li>Datos de identificación y contacto: nombre, correo electrónico y teléfono.</li><li>Información sobre el servicio solicitado: tipo de seguro, fianza o consultoría y la descripción que decidas proporcionar.</li><li>Información de atención: comunicaciones, solicitudes, datos de póliza y documentación necesaria para una cotización, administración o siniestro.</li><li>Datos técnicos básicos y la preferencia de cookies almacenada en tu navegador.</li></ul><p className="legal-note"><strong>Datos sensibles.</strong> La información de salud y ciertos datos relacionados con siniestros pueden ser sensibles. Evita enviarlos en el formulario general. Cuando sean necesarios, solicitaremos tu consentimiento expreso y te indicaremos un canal adecuado para compartirlos.</p>
<h2 id="finalidades">3. ¿Para qué utilizamos tus datos?</h2><h3>Finalidades primarias</h3><ul><li>Identificarte y responder tus solicitudes de información, cotización o asesoría.</li><li>Prestar atención sobre pólizas, renovaciones, documentos y siniestros.</li><li>Analizar tus necesidades y canalizar tu solicitud con aseguradoras, afianzadoras o proveedores pertinentes.</li><li>Mantener la seguridad de nuestros canales, prevenir abusos y cumplir obligaciones legales.</li></ul><h3>Finalidades secundarias</h3><p>Con tu autorización, podremos enviarte información de productos, prevención, novedades y seguimiento comercial. Puedes pedir que dejemos de hacerlo en cualquier momento escribiendo al correo de privacidad indicado arriba. Negarte a estas finalidades no afectará la atención de tu solicitud principal.</p>
<h2 id="derechos">4. Tus derechos ARCO</h2><p>Puedes solicitar el acceso, rectificación, cancelación u oposición al tratamiento de tus datos, así como revocar tu consentimiento o limitar su uso y divulgación. Envía tu solicitud a <a href="mailto:aguilar@grupohammurabi.com">aguilar@grupohammurabi.com</a> con tu nombre, un medio para comunicarte, la descripción clara del derecho que deseas ejercer y la información que permita localizar tus datos. Podremos pedirte documentación para acreditar tu identidad. Responderemos dentro de los plazos establecidos por la legislación aplicable.</p>
<h2 id="transferencias">5. Transferencias y encargados</h2><p>Cuando sea necesario para atender tu solicitud, tus datos podrán compartirse con aseguradoras, afianzadoras, ajustadores, prestadores de servicios y proveedores tecnológicos que actúen conforme a instrucciones y obligaciones de confidencialidad. También podremos comunicarlos a autoridades cuando exista una obligación legal. Cuando la ley exija tu consentimiento para una transferencia, lo solicitaremos previamente.</p><p>Si eliges continuar por WhatsApp, tus datos se transmitirán mediante ese servicio y estarán sujetos también a sus propias condiciones y políticas.</p>
<h2 id="cookies">6. Cookies y tecnologías similares</h2><p>Este sitio utiliza almacenamiento estrictamente necesario para recordar tu elección de cookies y permitir funciones básicas. Las tecnologías no esenciales —por ejemplo, analítica o publicidad— no se activarán sin tu autorización. Puedes aceptar todas o mantener únicamente las esenciales desde el aviso que aparece al visitar el sitio por primera vez.</p><p>Puedes eliminar o bloquear cookies desde la configuración de tu navegador. Si borras el almacenamiento del sitio, volveremos a solicitar tu preferencia. Deshabilitar las esenciales puede impedir que recordemos tu elección.</p>
<h2 id="seguridad">7. Conservación y seguridad</h2><p>Conservamos los datos solo durante el tiempo necesario para las finalidades descritas y los periodos legales o contractuales aplicables. Aplicamos medidas administrativas, técnicas y físicas razonables para evitar daño, pérdida, alteración, acceso o uso no autorizado.</p>
<h2 id="cambios">8. Cambios a este aviso</h2><p>Las modificaciones se publicarán en esta misma página indicando la fecha de actualización. Si un cambio requiere un nuevo consentimiento, lo solicitaremos por un medio apropiado.</p>
</div></section><SiteFooter/></main>}
