import Link from "next/link";

const services = [
  ["01","Personas","personas","Gastos Médicos, Vida, Casa Habitación y Automóviles.","Tu vida cambia. Tu protección puede acompañarte."],
  ["02","Empresas","empresas","RC, Property, D&O, Ingeniería, colectivos, flotillas y más.","Protección que entiende cómo se mueve tu negocio."],
  ["03","Fianzas","fianzas","Fidelidad, administrativas, judiciales, crédito y especiales.","Respaldo sólido para cumplir cada compromiso."],
  ["04","Gestión de riesgos","riesgos","Riesgos operacionales, laborales, estratégicos y otros.","Anticipar, decidir y avanzar con mayor certeza."]
];
function Header(){return <header className="nav shell"><Link className="brand" href="/" aria-label="Hammurabi Risk, inicio"><img src="/isotipo.jpg" alt="" /><span>Hammurabi Risk</span></Link><nav aria-label="Navegación principal"><a href="#servicios">Servicios</a><a href="#nosotros">Nosotros</a><a href="#experiencia">Experiencia</a><a href="#contacto">Contacto</a></nav><div className="header-actions"><a className="header-claim" href="tel:+526566696738">Reportar siniestro</a><a className="button small" href="#contacto">Cotiza ahora</a></div></header>}
export default function Home() {
  return <main>
    <Header />
    <section className="hero shell"><div className="hero-copy"><p className="eyebrow">Broker mexicano · 30 años de experiencia</p><h1>Riesgos bajo control.<br /><em>Tranquilidad en marcha.</em></h1><p className="lead">Gestión, consultoría y asesoramiento cercano en riesgos, seguros y fianzas para proteger lo que más valoras.</p><div className="hero-actions"><a className="button" href="#servicios">Encuentra tu cobertura</a><a className="text-link" href="#nosotros">Conócenos <span>→</span></a></div><div className="trust"><strong>30+</strong><span>años resolviendo<br />con honestidad</span></div></div><div className="hero-art hero-protection"><div className="orbit orbit-one">24/7</div><div className="orbit orbit-two">✓</div><img src="/proteccion-riesgos-paraguas.png" alt="Paraguas que protege a una familia, una vivienda, una empresa y un automóvil" /><p>Protección para todo lo que importa.</p></div></section>
    <section className="ticker"><div>PERSONAS <i>✦</i> EMPRESAS <i>✦</i> FIANZAS <i>✦</i> GESTIÓN DE RIESGOS <i>✦</i></div></section>
    <section className="services-preview shell" id="servicios"><p className="eyebrow">Todo lo que necesitas</p><div className="section-heading"><h2>Protección hecha<br />para tu mundo.</h2><p>Te ayudamos a elegir bien, sin letras chiquitas ni explicaciones complicadas.</p></div><div className="service-grid">{services.map(([n,title,slug,text,tag])=><Link href={`/servicios/${slug}`} className="service-card" key={slug}><span>{n}</span><h3>{title}</h3><p>{text}</p><small>{tag}</small><b>Explorar →</b></Link>)}</div></section>
    <section className="about" id="nosotros"><div className="about-inner shell"><div className="about-visual"><div className="blue-disc"></div><img src="/mascota-camina.png" alt="Mascota de Hammurabi Risk caminando" /></div><div className="about-copy"><p className="eyebrow light">¿Quiénes somos?</p><h2>Consultoría con<br />honestidad y empatía.</h2><p>Somos un broker mexicano con más de 30 años de experiencia. Nos distinguimos por un servicio personalizado y soluciones diseñadas para proteger lo que más valoras con confianza, cercanía y responsabilidad.</p><div className="values"><div><span>01</span><h3>Garantía</h3><p>Honestidad y calidad incluidas en cada operación y consultoría.</p></div><div><span>02</span><h3>Compromiso</h3><p>Asesoría experta y transparente, respondiendo en los momentos clave.</p></div></div></div></div></section>
    <section className="difference shell" id="experiencia"><p className="eyebrow">Experiencia y calidad</p><h2>¿Qué nos distingue?</h2><div className="difference-grid">{[["Asesoría","Te explicamos las cláusulas y el nivel real de protección de tu seguro."],["Seguimiento","Atención personalizada durante la vigencia y recordatorios puntuales de renovación."],["Atención en siniestros","Estamos para asesorarte y apoyarte, sin importar el tipo de siniestro."],["Gestión de incidencias","Protegemos tus derechos y damos seguimiento a tu caso hasta resolverlo."]].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
    <section className="incidents"><div className="shell incident-grid"><div><p className="eyebrow light">Estamos de tu lado</p><h2>Tu póliza no termina cuando la firmas.</h2><p>Actuamos como tu enlace con la aseguradora, protegiendo tus derechos y brindándote apoyo en caso de siniestro. Nuestra prioridad es tu seguridad y bienestar, con ética y compromiso en todo momento.</p></div><div className="keys"><h3>Nuestras 5 claves de servicio</h3>{["Asesoría personalizada","Seguimiento constante","Gestión total","Atención 24/7","Comunicación y transparencia"].map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}</div></div></section>
    <section className="purpose shell"><div><p className="eyebrow">Misión</p><h3>Gestión de riesgos a la medida.</h3><p>Implementar una gestión conforme a la necesidad de cada empresa y persona, afrontando positivamente los cambios del mercado, normativos y regulatorios, las exigencias de clientes y el nacimiento de nuevos riesgos.</p></div><div><p className="eyebrow">Visión</p><h3>Liderar con soluciones innovadoras.</h3><p>Ser líderes nacionales en consultoría de riesgos, corretaje de seguros y fianzas, ofreciendo soluciones que brinden seguridad a nuestros clientes.</p></div></section>
    <section className="risk-detail"><div className="shell"><p className="eyebrow light">Especialistas en consultoría de riesgos</p><div className="risk-head"><h2>Prevención basada<br />en buenas prácticas.</h2><p>Nuestro principio de administración se centra en la norma ISO 31000 y en las mejores prácticas de nuestros socios en Latinoamérica y España.</p></div><div className="risk-steps">{[["01","Entendemos el entorno","Marcos reguladores y políticas internas o externas pueden afectar las operaciones y el libre comercio."],["02","Alineamos objetivos","Una buena gestión mejora la calidad y permite actuar correctamente ante la materialización de un riesgo."],["03","Prevenimos","Buscamos la mejor preparación ante riesgos operativos, fortuitos, estratégicos o financieros."],["04","Decidimos en equipo","Facilitamos decisiones informadas para las personas involucradas en cada nivel de la organización."]].map(([n,t,p])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="alliances shell"><div><p className="eyebrow">Alianzas</p><h2>Trabajamos de la mano con las mejores compañías</h2><p>Colaboramos con aseguradoras líderes para encontrar la alternativa adecuada para ti.</p></div><img src="/mascota-perfil.png" alt="Mascota de Hammurabi Risk mirando hacia las alianzas" /><div className="alliance-logos">{[["afirme.jpg","Afirme Seguros"],["qualitas.jpg","Quálitas"],["chubb.jpg","Chubb"],["gmx.jpg","GMX Seguros"],["atlas.jpg","Seguros Atlas"],["allianz.jpg","Allianz"],["axa.jpg","AXA"],["hdi.jpg","HDI Seguros"],["sura.png","SURA"],["metlife.png","MetLife"]].map(([file,name])=><div className="alliance-logo" key={file}><img src={`/alianzas/${file}`} alt={`Logotipo de ${name}`} /></div>)}</div><h3 className="alliance-subtitle">Y también de las mejores afianzadoras.</h3><div className="alliance-logos surety-logos">{[["liberty-finanzas.avif","Liberty Fianzas"],["aserta.png","Aserta"],["sofimex.png","Sofimex"]].map(([file,name])=><div className="alliance-logo" key={file}><img src={`/alianzas/${file}`} alt={`Logotipo de ${name}`} /></div>)}</div></section>
    <section className="contact contact-redesign" id="contacto"><div className="shell"><div className="contact-heading"><p className="eyebrow">Estamos para ayudarte</p><h2>¿Cómo podemos ayudarte hoy?</h2><p>Elige el tipo de atención que necesitas. Nuestro equipo te acompañará de forma clara y cercana.</p></div><div className="contact-options"><article className="contact-option"><div className="contact-option-top"><span className="contact-icon">✦</span><b>Nuevo cliente</b></div><h3>Cotizaciones</h3><p>Encuentra la cobertura adecuada para ti, tu familia o tu empresa.</p><a className="contact-phone" href="tel:+526561423870"><span>☎</span>656 142 3870</a><div className="contact-person"><strong>Adriana Aguilar Franco</strong><a href="mailto:aguilar@grupohammurabi.com">aguilar@grupohammurabi.com</a></div><a className="button" href="mailto:aguilar@grupohammurabi.com?subject=Quiero%20una%20cotización">Solicitar cotización</a></article><article className="contact-option"><div className="contact-option-top"><span className="contact-icon">◎</span><b>Clientes actuales</b></div><h3>Atención y pólizas</h3><p>Cambios, renovaciones, documentos o cualquier duda sobre tu póliza.</p><a className="contact-phone" href="tel:+526561423871"><span>☎</span>656 142 3871</a><div className="contact-person"><strong>Enrique Damián Rodríguez Aguilar</strong><a href="mailto:erodriguez@grupohammurabi.com">erodriguez@grupohammurabi.com</a></div><a className="contact-text-link" href="mailto:erodriguez@grupohammurabi.com?subject=Necesito%20ayuda%20con%20mi%20póliza">Escribir a atención <span>→</span></a></article><article className="contact-option contact-option-dark"><div className="contact-option-top"><span className="contact-icon">✓</span><b>Atención 24/7</b></div><h3>Siniestros</h3><p>Cuando sucede algo, respondemos. Te asesoramos y acompañamos durante todo el proceso.</p><a className="contact-phone" href="tel:+526566696738"><span>☎</span>656 669 6738</a><div className="claim-box"><strong>¿Tuviste un siniestro?</strong><p>Llámanos para orientarte y actuar como enlace con la aseguradora, protegiendo tus derechos.</p></div><a className="button claim-button" href="tel:+526566696738">Reportar un siniestro</a></article></div><address className="contact-address">Plaza Hatria · Blvd. Gómez Morín, local 17 · Ciudad Juárez, Chihuahua</address></div></section>
    <footer><div className="shell footer-top"><Link className="brand inverse" href="/"><img src="/isotipo.jpg" alt="" /><span>Hammurabi Risk</span></Link><div><a href="https://www.facebook.com/GrupoHammurabi">Facebook</a><a href="https://www.instagram.com/hammurabirisk">Instagram</a><a href="https://www.linkedin.com">LinkedIn</a></div><a href="tel:+526566696738">Tel. 656 669 6738</a></div><div className="shell copyright">© 2026 Hammurabi Risk · Consultores de riesgos y seguros</div></footer>
  </main>
}
