import type { Metadata } from "next";
import LegalHeader from "../LegalHeader";
import SiteFooter from "../SiteFooter";
export const dynamic = "force-static";
export const metadata: Metadata = {title:"Términos y condiciones",description:"Términos de uso del sitio web de Hammurabi Risk.",alternates:{canonical:"/terminos-condiciones"}};

export default function TermsPage(){return <main className="legal-page"><LegalHeader/><section className="legal-hero shell"><p className="eyebrow">Información clara</p><h1>Términos y condiciones.</h1><p className="lead">Estas condiciones regulan el uso del sitio y nuestros canales digitales de información y contacto.</p><p className="legal-updated">Última actualización: 23 de agosto de 2026</p></section><section className="legal-content shell"><aside className="legal-index" aria-label="Contenido"><strong>En esta página</strong><a href="#aceptacion">Aceptación</a><a href="#servicio">Alcance</a><a href="#cotizaciones">Cotizaciones</a><a href="#usuario">Responsabilidad del usuario</a><a href="#propiedad">Propiedad intelectual</a><a href="#privacidad">Privacidad</a><a href="#ley">Ley aplicable</a></aside><div className="legal-copy">
<h2 id="aceptacion">1. Aceptación y datos de contacto</h2><p>Al navegar en este sitio aceptas estos términos. Si no estás de acuerdo, puedes dejar de utilizarlo. El sitio es operado bajo la marca Hammurabi Risk, con domicilio en Plaza Hatria, Blvd. Gómez Morín, local 17, Ciudad Juárez, Chihuahua. Puedes contactarnos en <a href="mailto:aguilar@grupohammurabi.com">aguilar@grupohammurabi.com</a> o al <a href="tel:+526566696738">656 669 6738</a>.</p>
<h2 id="servicio">2. Alcance del sitio</h2><p>El contenido tiene fines informativos y permite solicitar contacto sobre consultoría de riesgos, seguros y fianzas. La información general del sitio no constituye asesoría definitiva, oferta vinculante, contrato de seguro, fianza ni garantía de aceptación o cobertura.</p>
<h2 id="cotizaciones">3. Cotizaciones, pólizas y cobertura</h2><p>Las solicitudes enviadas por formularios, correo, teléfono o WhatsApp son peticiones de contacto. Toda cotización está sujeta al análisis, requisitos, vigencia y condiciones de la aseguradora o afianzadora correspondiente. La cobertura solo inicia cuando exista confirmación expresa, emisión de la póliza o contrato y cumplimiento de los requisitos y pagos aplicables.</p><p>En caso de diferencia, prevalecerán la carátula, condiciones generales, endosos y demás documentos emitidos por la aseguradora o afianzadora. Hammurabi Risk explicará la información disponible y acompañará al cliente, sin sustituir las decisiones ni obligaciones de dichas instituciones.</p>
<h2 id="usuario">4. Uso correcto y responsabilidad del usuario</h2><p>Te comprometes a proporcionar información verdadera, vigente y suficiente; revisar los datos de solicitudes y documentos; y no utilizar el sitio con fines ilícitos, fraudulentos o que afecten su operación. No envíes información sensible que no te haya sido solicitada ni datos de terceros sin autorización.</p>
<h2 id="disponibilidad">5. Disponibilidad y enlaces externos</h2><p>Procuramos mantener la información correcta y el sitio disponible, pero puede haber interrupciones, mantenimiento o cambios. Los enlaces a WhatsApp, redes sociales, aseguradoras u otros sitios son operados por terceros y se rigen por sus propias condiciones. Nada en estos términos limita los derechos irrenunciables que te correspondan como consumidor.</p>
<h2 id="propiedad">6. Propiedad intelectual</h2><p>La marca, logotipos, mascota, diseño, textos y demás contenidos propios están protegidos por la legislación aplicable. Puedes consultar el sitio para fines personales e informativos; no puedes reproducir, explotar o modificar sus elementos con fines comerciales sin autorización previa y por escrito.</p>
<h2 id="privacidad">7. Privacidad y cookies</h2><p>El tratamiento de datos personales se explica en nuestro <a href="/aviso-privacidad">aviso de privacidad</a>. El sitio recuerda tu elección de cookies y no debe activar tecnologías no esenciales sin tu autorización.</p>
<h2 id="cambios">8. Modificaciones</h2><p>Podemos actualizar el contenido y estos términos. La versión vigente será la publicada en esta página con su fecha de actualización. Los cambios no afectarán derechos ya adquiridos ni contratos celebrados.</p>
<h2 id="ley">9. Legislación aplicable</h2><p>Estos términos se interpretan conforme a las leyes de los Estados Unidos Mexicanos. Cualquier controversia se atenderá ante las autoridades competentes, respetando los derechos y mecanismos de protección disponibles para las personas consumidoras.</p>
</div></section><SiteFooter/></main>}
